name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cpu: x86_64
          - os: ubuntu-22.04-arm
            cpu: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y libsfml-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Copy dynamic libraries to executable (x86_64 CPU)
      if: matrix.cpu == 'x86_64'
      run: |
        cp /usr/lib/x86_64-linux-gnu/libsfml-{audio,graphics,system,window}.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libfreetype*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libpng*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libvorbis*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libogg*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libFLAC*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libstb*.so* ${{github.workspace}}/build

    - name: Copy dynamic libraries to executable (arm64 CPU)
      if: matrix.cpu == 'arm64'
      run: |
        cp /usr/lib/aarch64-linux-gnu/libsfml-{audio,graphics,system,window}.so* ${{github.workspace}}/build
        cp /usr/lib/aarch64-linux-gnu/libfreetype*.so* ${{github.workspace}}/build
        cp /usr/lib/aarch64-linux-gnu/libpng*.so* ${{github.workspace}}/build
        cp /usr/lib/aarch64-linux-gnu/libvorbis*.so* ${{github.workspace}}/build
        cp /usr/lib/aarch64-linux-gnu/libogg*.so* ${{github.workspace}}/build
        cp /usr/lib/aarch64-linux-gnu/libFLAC*.so* ${{github.workspace}}/build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chess-linux-${{matrix.cpu}}
        path: |
          build/Chess
          build/resources/
          build/lib*.so*

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.27.x'

    - name: Install dependencies
      run: |
        curl -LO https://github.com/SFML/SFML/releases/download/2.6.2/SFML-2.6.2-windows-vc17-64-bit.zip
        7z x SFML-2.6.2-windows-vc17-64-bit.zip

    - name: Configure CMake
      run: >-
        cmake -B ${{github.workspace}}\build
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="$<1:${{github.workspace}}\build>"
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="$<1:${{github.workspace}}\build>"
        -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY="$<1:${{github.workspace}}\build>"
        -DCMAKE_PREFIX_PATH=${{github.workspace}}\SFML-2.6.2\lib\cmake\SFML

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: Copy dynamic libraries to executable
      run: |
        xcopy ${{github.workspace}}\SFML-2.6.2\bin\openal32.dll ${{github.workspace}}\build\
        xcopy ${{github.workspace}}\SFML-2.6.2\bin\sfml-audio-2.dll ${{github.workspace}}\build\
        xcopy ${{github.workspace}}\SFML-2.6.2\bin\sfml-graphics-2.dll ${{github.workspace}}\build\
        xcopy ${{github.workspace}}\SFML-2.6.2\bin\sfml-system-2.dll ${{github.workspace}}\build\
        xcopy ${{github.workspace}}\SFML-2.6.2\bin\sfml-window-2.dll ${{github.workspace}}\build\

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chess-windows-x86_64
        path: |
          build/Chess.exe
          build/resources/
          build/*.dll

  build-macos:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            cpu: x86_64
          - os: macos-latest
            cpu: arm64

    steps:
    - uses: actions/checkout@v4
  
    - name: Install dependencies
      run: brew install sfml@2 && brew link sfml@2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Copy dynamic libraries to executable (x86_64 CPU)
      if: matrix.cpu == 'x86_64'
      run: |
        cp /usr/local/lib/libsfml-{audio,graphics,system,window}*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libfreetype*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libpng*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libvorbis*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libogg*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libFLAC*.dylib ${{github.workspace}}/build

    - name: Copy dynamic libraries to executable (arm64 CPU)
      if: matrix.cpu == 'arm64'
      run: |
        cp /opt/homebrew/Cellar/sfml@2/*/lib/libsfml-{audio,graphics,system,window}*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/freetype/*/lib/libfreetype*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/libpng/*/lib/libpng*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/libvorbis/*/lib/libvorbis*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/libogg/*/lib/libogg*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/flac/*/lib/libFLAC*.dylib ${{github.workspace}}/build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chess-macos-${{matrix.cpu}}
        path: |
          build/Chess
          build/resources/
          build/lib*.dylib
