name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y libsfml-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Copy resources and libraries to executable
      run: |
        cp -r ${{github.workspace}}/resources ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libsfml-{audio,graphics,system,window}.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libfreetype*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libpng*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libvorbis*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libogg*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libFLAC*.so* ${{github.workspace}}/build
        cp /usr/lib/x86_64-linux-gnu/libstb*.so* ${{github.workspace}}/build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chess-linux
        path: |
          build/Chess
          build/resources/
          build/lib*.so*
  
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.27.x'

    - name: Install dependencies
      run: |
        git clone https://github.com/Microsoft/vcpkg.git ${{github.workspace}}\vcpkg --depth 1
        ${{github.workspace}}\vcpkg\bootstrap-vcpkg.bat -disableMetrics
        ${{github.workspace}}\vcpkg\vcpkg integrate install
        ${{github.workspace}}\vcpkg\vcpkg install sfml:x64-windows

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: Copy resources to executable
      run: xcopy /s /i ${{github.workspace}}\resources ${{github.workspace}}\build\${{env.BUILD_TYPE}}\resources

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chess-windows
        path: |
          build\${{env.BUILD_TYPE}}

  build-macos:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            cpu: intel
          - os: macos-latest
            cpu: amd

    steps:
    - uses: actions/checkout@v4
  
    - name: Install dependencies
      run: brew install sfml

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Copy resources and libraries to executable (Intel CPU)
      if: matrix.cpu == 'intel'
      run: |
        cp -r ${{github.workspace}}/resources ${{github.workspace}}/build
        cp /usr/local/lib/libsfml-{audio,graphics,system,window}*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libfreetype*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libpng*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libvorbis*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libogg*.dylib ${{github.workspace}}/build
        cp /usr/local/lib/libFLAC*.dylib ${{github.workspace}}/build

    - name: Copy resources and libraries to executable (AMD CPU)
      if: matrix.cpu == 'amd'
      run: |
        cp -r ${{github.workspace}}/resources ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/sfml/*/lib/libsfml-{audio,graphics,system,window}*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/freetype/*/lib/libfreetype*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/libpng/*/lib/libpng*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/libvorbis/*/lib/libvorbis*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/libogg/*/lib/libogg*.dylib ${{github.workspace}}/build
        cp /opt/homebrew/Cellar/flac/*/lib/libFLAC*.dylib ${{github.workspace}}/build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chess-macos-${{matrix.cpu}}
        path: |
          build/Chess
          build/resources/
          build/lib*.dylib
